version: '3.1'

services:
  ganachecli:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545
  web:
    build:
      context: .
      dockerfile: ./docker/express/Dockerfile
    container_name: vota_ex01
    command: bash -c "npm install --quiet && nodemon app.js"
    env_file:
     - ./.env
    hostname: vota_ex01
    ports:
      - "3000:3000"
    volumes:
      - ./client:/code
      - /code/node_modules
    restart: always
  nginx:
    container_name: vota_ng01
    build:
      context: .
      dockerfile: ./docker/nginx/production.Dockerfile
    depends_on:
      - web
    environment:
      - PUID=1001
      - PGID=1001
      - EMAIL=erick@agrazal.com
      - URL=vota.erickagrazal.com
      - TZ=America/Panama
    hostname: vota_ng01
    links:
      - web:web
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: always